# Config file for automatic testing at travis-ci.org

language: python

python:
  - "pypy3"
  - "pypy"
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"

# Use container-based infrastructure
sudo: false

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U pip
  - pip install -U pytest

# command to run tests, e.g. python setup.py test
script:
  - python ./setup.py develop
  - pytest test/*

after_script:
- pip install pycodestyle pyflakes
- pyflakes . | tee >(wc -l)           # static analysis
- pycodestyle --statistics --count .  # static analysis
