language: python
python:
- pypy3
- pypy
- '3.6'
- '3.5'
- '3.4'
- '2.7'
sudo: false
install:
- pip install -U pip
- pip install -U pytest
script:
- python ./setup.py develop
- pytest tests/*
deploy:
  provider: pypi
  user: davidlday
  python: '3.6'
  password:
    secure: Sqbs5JjSDlgfhfDjqBUQibtFkonfOr7WOIXRcGywclcb/BoblK2i6y5TMZE4Le0aMwtmWZ72CruIJu31H010HzVi2LuH+l6MiDdkDJW5J54ctnCXi9jysvp2iHt7EXsFMG5tMwbc0fQtnPGskaBq7WFt/NMkPyFfodIJa/OAWaMDPCLXaultDzcLCGCVD9EAJCz49cEJeYCGPBY5bCwwsq95OmM/71snJNoWwIhsl8x9wydsTEqESNokrSXzk52+YJ1eWmIP8dFn7mcHroveAEaV7raHprNDTskBLvkfDYiaqvjOb+VHYk/HxHvJOAqDdBvJSzhA18PjmFkfdxveV/BehbvGzBCrQU4hNNP9HdPFyx0wU2xkPeEC6BlSqzYpx/esvAcFJYFEeGZlX8ciDIaCYynRe40EbeQQgI4QSiisMsZ0PyBzOCJ271yoxzrqYlTrlsEkTfp9o1x9HX6hQwRPjMoIVnBHB8jKginkPjXLuxythOQ14/1+D11He6HHrFiYVQ2TSJwA/bOuuJVolrXWwwM52LB7JjoF9jr79V+/804ZzfWehVBChmaDl+hZLxqcJ7LExHhvCKB08p8yRZeWdtttBsxQMCa+7NAVwiZSOTSg4jnqlMKLR9be3eblGkeQkWFNOpbA1LP89amIixhi91zBY7bEP6HOXlMR2gg=
  distributions: sdist bdist_wheel
  on:
    tags: true
